### ISSUE TITLE
Implement CI/CD pipeline

### ISSUE THREAD

**Issue by kieranpotts** [kieranpotts/resume#1]
```yaml
name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build in docker
        run: docker run --mount type=bind,source="${PWD}",target=/data $IMAGE /data/build.sh
        env:
          IMAGE: blang/latex:ctanfull
      - uses: actions/upload-artifact@v4.4.3
        with:
          name: pdf
          path: 'dist/cv.pdf'
```
